local modSupport = {}
local g = require("src_dorky.dorkyGlobals")

---@param player EntityPlayer
function modSupport:AddCCPSupport(player, ccp)
	ccp:AddPlayer(
		player,
		g.PLAYER_DORKY,
		"gfx/characters/costumes/character_dorky.png",
		g.COSTUME_DORKY_FLIGHT,
		nil,
		g.COSTUME_DORKY
	)
	ccp:ItemCostumeWhitelist(
		g.PLAYER_DORKY,
		{
			[g.COLLECTIBLE_TONGUE_GRAPPLE] = true,
			[CollectibleType.COLLECTIBLE_MOMS_BRA] = true,
			[CollectibleType.COLLECTIBLE_HEART] = true,
			[CollectibleType.COLLECTIBLE_9_VOLT] = true,
			[CollectibleType.COLLECTIBLE_BELT] = true,
			[CollectibleType.COLLECTIBLE_BLOOD_OF_THE_MARTYR] = true,
			[CollectibleType.COLLECTIBLE_BOOM] = true,
			[CollectibleType.COLLECTIBLE_CUPIDS_ARROW] = true,
			[CollectibleType.COLLECTIBLE_DEAD_BIRD] = true,
			[CollectibleType.COLLECTIBLE_DR_FETUS] = true,
			[CollectibleType.COLLECTIBLE_LOKIS_HORNS] = true,
			[CollectibleType.COLLECTIBLE_LUCKY_FOOT] = true,
			[CollectibleType.COLLECTIBLE_MARK] = true,
			[CollectibleType.COLLECTIBLE_KAMIKAZE] = true,
			[CollectibleType.COLLECTIBLE_MOMS_HEELS] = true,
			[CollectibleType.COLLECTIBLE_MOMS_UNDERWEAR] = true,
			[CollectibleType.COLLECTIBLE_MONEY_EQUALS_POWER] = true,
			[CollectibleType.COLLECTIBLE_MY_REFLECTION] = true,
			[CollectibleType.COLLECTIBLE_PARASITE] = true,
			[CollectibleType.COLLECTIBLE_PHD] = true,
			[CollectibleType.COLLECTIBLE_SKATOLE] = true,
			[CollectibleType.COLLECTIBLE_SMALL_ROCK] = true,
			[CollectibleType.COLLECTIBLE_SPELUNKER_HAT] = true,
			[CollectibleType.COLLECTIBLE_SPIDER_BITE] = true,
			[CollectibleType.COLLECTIBLE_STEAM_SALE] = true,
			[CollectibleType.COLLECTIBLE_STEVEN] = true,
			[CollectibleType.COLLECTIBLE_SUPER_BANDAGE] = true,
			[CollectibleType.COLLECTIBLE_ROSARY] = true,
			[CollectibleType.COLLECTIBLE_WIRE_COAT_HANGER] = true,
			[CollectibleType.COLLECTIBLE_XRAY_VISION] = true,
			[CollectibleType.COLLECTIBLE_BLOODY_LUST] = true,
			[CollectibleType.COLLECTIBLE_DEAD_DOVE] = true,
			[CollectibleType.COLLECTIBLE_EPIC_FETUS] = true,
			[CollectibleType.COLLECTIBLE_MOMS_COIN_PURSE] = true,
			[CollectibleType.COLLECTIBLE_PAGEANT_BOY] = true,
			[CollectibleType.COLLECTIBLE_PEEPER] = true,
			[CollectibleType.COLLECTIBLE_SCOOPER] = true,
			[CollectibleType.COLLECTIBLE_PYRO] = true,
			[CollectibleType.COLLECTIBLE_SCAPULAR] = true,
			[CollectibleType.COLLECTIBLE_TECHNOLOGY] = true,
			[CollectibleType.COLLECTIBLE_TECH_X] = true,
			[CollectibleType.COLLECTIBLE_TECH_5] = true,
			[CollectibleType.COLLECTIBLE_HALO] = true,
			[CollectibleType.COLLECTIBLE_GUPPYS_TAIL] = true,
			[CollectibleType.COLLECTIBLE_MOMS_PURSE] = true,
			[CollectibleType.COLLECTIBLE_SPIRIT_OF_THE_NIGHT] = true,
			[CollectibleType.COLLECTIBLE_ANKH] = true,
			[CollectibleType.COLLECTIBLE_MITRE] = true,
			[CollectibleType.COLLECTIBLE_BOX] = true,
			[CollectibleType.COLLECTIBLE_MOMS_EYESHADOW] = true,
			[CollectibleType.COLLECTIBLE_IRON_BAR] = true,
			[CollectibleType.COLLECTIBLE_MIDAS_TOUCH] = true,
			[CollectibleType.COLLECTIBLE_FANNY_PACK] = true,
			[CollectibleType.COLLECTIBLE_SHARP_PLUG] = true,
			[CollectibleType.COLLECTIBLE_CHAMPION_BELT] = true,
			[CollectibleType.COLLECTIBLE_GNAWED_LEAF] = true,
			[CollectibleType.COLLECTIBLE_GUPPYS_COLLAR] = true,
			[CollectibleType.COLLECTIBLE_CEREMONIAL_ROBES] = true,
			[CollectibleType.COLLECTIBLE_OLD_BANDAGE] = true,
			[CollectibleType.COLLECTIBLE_BLACK_LOTUS] = true,
			[CollectibleType.COLLECTIBLE_TINY_PLANET] = true,
			[CollectibleType.COLLECTIBLE_CONTRACT_FROM_BELOW] = true,
			[CollectibleType.COLLECTIBLE_INFAMY] = true,
			[CollectibleType.COLLECTIBLE_20_20] = true,
			[CollectibleType.COLLECTIBLE_HIVE_MIND] = true,
			[CollectibleType.COLLECTIBLE_LITTLE_BAGGY] = true,
			[CollectibleType.COLLECTIBLE_BLOOD_CLOT] = true,
			[CollectibleType.COLLECTIBLE_SCREW] = true,
			[CollectibleType.COLLECTIBLE_HOT_BOMBS] = true,
			[CollectibleType.COLLECTIBLE_FIRE_MIND] = true,
			[CollectibleType.COLLECTIBLE_MISSING_PAGE_2] = true,
			[CollectibleType.COLLECTIBLE_ROBO_BABY_2] = true,
			[CollectibleType.COLLECTIBLE_VIRGO] = true,
			[CollectibleType.COLLECTIBLE_AQUARIUS] = true,
			[CollectibleType.COLLECTIBLE_MAGGYS_BOW] = true,
			[CollectibleType.COLLECTIBLE_STRANGE_ATTRACTOR] = true,
			[CollectibleType.COLLECTIBLE_CURSED_EYE] = true,
			[CollectibleType.COLLECTIBLE_MYSTERIOUS_LIQUID] = true,
			[CollectibleType.COLLECTIBLE_POLAROID] = true,
			[CollectibleType.COLLECTIBLE_NEGATIVE] = true,
			[CollectibleType.COLLECTIBLE_SAFETY_PIN] = true,
			[CollectibleType.COLLECTIBLE_LATCH_KEY] = true,
			[CollectibleType.COLLECTIBLE_MATCH_BOOK] = true,
			[CollectibleType.COLLECTIBLE_TOXIC_SHOCK] = true,
			[CollectibleType.COLLECTIBLE_BOMBER_BOY] = true,
			[CollectibleType.COLLECTIBLE_CRACK_JACKS] = true,
			[CollectibleType.COLLECTIBLE_MOMS_PEARLS] = true,
			[CollectibleType.COLLECTIBLE_MR_DOLLY] = true,
			[CollectibleType.COLLECTIBLE_CURSE_OF_THE_TOWER] = true,
			[CollectibleType.COLLECTIBLE_DEAD_EYE] = true,
			[CollectibleType.COLLECTIBLE_HOLY_LIGHT] = true,
			[CollectibleType.COLLECTIBLE_HOST_HAT] = true,
			[CollectibleType.COLLECTIBLE_PAY_TO_PLAY] = true,
			[CollectibleType.COLLECTIBLE_EDENS_BLESSING] = true,
			[CollectibleType.COLLECTIBLE_TRACTOR_BEAM] = true,
			[CollectibleType.COLLECTIBLE_PURITY] = true,
			[CollectibleType.COLLECTIBLE_ATHAME] = true,
			[CollectibleType.COLLECTIBLE_EMPTY_VESSEL] = true,
			[CollectibleType.COLLECTIBLE_BLACK_POWDER] = true,
			[CollectibleType.COLLECTIBLE_NIGHT_LIGHT] = true,
			[CollectibleType.COLLECTIBLE_PJS] = true,
			[CollectibleType.COLLECTIBLE_HEAD_OF_THE_KEEPER] = true,
			[CollectibleType.COLLECTIBLE_GLITTER_BOMBS] = true,
			[CollectibleType.COLLECTIBLE_MY_SHADOW] = true,
			[CollectibleType.COLLECTIBLE_LEAD_PENCIL] = true,
			[CollectibleType.COLLECTIBLE_LINGER_BEAN] = true,
			[CollectibleType.COLLECTIBLE_EYE_OF_GREED] = true,
			[CollectibleType.COLLECTIBLE_TAROT_CLOTH] = true,
			[CollectibleType.COLLECTIBLE_EYE_OF_BELIAL] = true,
			[CollectibleType.COLLECTIBLE_GLYPH_OF_BALANCE] = true,
			[CollectibleType.COLLECTIBLE_JACOBS_LADDER] = true,
			[CollectibleType.COLLECTIBLE_CAMO_UNDIES] = true,
			[CollectibleType.COLLECTIBLE_DUALITY] = true,
			[CollectibleType.COLLECTIBLE_EUCHARIST] = true,
			[CollectibleType.COLLECTIBLE_GREEDS_GULLET] = true,
			[CollectibleType.COLLECTIBLE_LITTLE_HORN] = true,
			[CollectibleType.COLLECTIBLE_SHARP_STRAW] = true,
			[CollectibleType.COLLECTIBLE_BOZO] = true,
			[CollectibleType.COLLECTIBLE_FAST_BOMBS] = true,
			[CollectibleType.COLLECTIBLE_DEATHS_LIST] = true,
			[CollectibleType.COLLECTIBLE_BLANKET] = true,
			[CollectibleType.COLLECTIBLE_MARROW] = true,
			[CollectibleType.COLLECTIBLE_DADS_RING] = true,
			[CollectibleType.COLLECTIBLE_BATTERY] = true,
			[CollectibleType.COLLECTIBLE_STOP_WATCH] = true,
			[CollectibleType.COLLECTIBLE_BROKEN_WATCH] = true,
			[CollectibleType.COLLECTIBLE_LAZARUS_RAGS] = true,
			[CollectibleType.COLLECTIBLE_MOMS_KEY] = true,
			[CollectibleType.COLLECTIBLE_MONSTROS_TOOTH] = true,
			[CollectibleType.COLLECTIBLE_SOUL] = true,
			[CollectibleType.COLLECTIBLE_120_VOLT] = true,
			[CollectibleType.COLLECTIBLE_BLOOD_OATH] = true,
			[CollectibleType.COLLECTIBLE_SOCKS] = true,
			[CollectibleType.COLLECTIBLE_MONSTRANCE] = true,
			[CollectibleType.COLLECTIBLE_SOL] = true,
			[CollectibleType.COLLECTIBLE_MERCURIUS] = true,
			[CollectibleType.COLLECTIBLE_ACT_OF_CONTRITION] = true,
			[CollectibleType.COLLECTIBLE_MEMBER_CARD] = true,
			[CollectibleType.COLLECTIBLE_BATTERY_PACK] = true,
			[CollectibleType.COLLECTIBLE_BIRD_CAGE] = true,
			[CollectibleType.COLLECTIBLE_BLOOD_BOMBS] = true,
			[CollectibleType.COLLECTIBLE_BIRDS_EYE] = true,
			[CollectibleType.COLLECTIBLE_EVIL_CHARM] = true,
			[CollectibleType.COLLECTIBLE_CONSOLATION_PRIZE] = true,
			[CollectibleType.COLLECTIBLE_LARYNX] = true,
			[CollectibleType.COLLECTIBLE_GUPPYS_EYE] = true,
			[CollectibleType.COLLECTIBLE_CRACKED_ORB] = true,
			[CollectibleType.COLLECTIBLE_C_SECTION] = true,
			[CollectibleType.COLLECTIBLE_SOUL_LOCKET] = true,
			[CollectibleType.COLLECTIBLE_BERSERK] = true,
			[CollectibleType.COLLECTIBLE_GLASS_EYE] = true,
		}
	)
	ccp:NullItemIDWhitelist(
		g.PLAYER_DORKY,
		{
			[NullItemID.ID_PUBERTY] = true,
			[NullItemID.ID_EMPTY_VESSEL] = true,
			[NullItemID.ID_BOOKWORM] = true,
			[NullItemID.ID_MOM] = true,
			[NullItemID.ID_DOUBLE_GUPPYS_EYE] = true,
			[NullItemID.ID_DOUBLE_GLASS_EYE] = true,
			[NullItemID.ID_CHRISTMAS] = true,
			[NullItemID.ID_BLINDFOLD] = true,
			[NullItemID.ID_BATWING_WINGS] = true
		}
	)
	ccp:AddPlayer(
		player,
		g.PLAYER_SPIRIT,
		"gfx/characters/costumes/character_spirit.png",
		nil,
		nil,
		g.COSTUME_SPIRIT
	)
	ccp:ItemCostumeWhitelist(
		g.PLAYER_SPIRIT,
		{
			[CollectibleType.COLLECTIBLE_MOMS_BRA] = true,
			[CollectibleType.COLLECTIBLE_HEART] = true,
			[CollectibleType.COLLECTIBLE_9_VOLT] = true,
			[CollectibleType.COLLECTIBLE_BELT] = true,
			[CollectibleType.COLLECTIBLE_BLOOD_OF_THE_MARTYR] = true,
			[CollectibleType.COLLECTIBLE_BOOM] = true,
			[CollectibleType.COLLECTIBLE_CUPIDS_ARROW] = true,
			[CollectibleType.COLLECTIBLE_DEAD_BIRD] = true,
			[CollectibleType.COLLECTIBLE_DR_FETUS] = true,
			[CollectibleType.COLLECTIBLE_LOKIS_HORNS] = true,
			[CollectibleType.COLLECTIBLE_LUCKY_FOOT] = true,
			[CollectibleType.COLLECTIBLE_MARK] = true,
			[CollectibleType.COLLECTIBLE_KAMIKAZE] = true,
			[CollectibleType.COLLECTIBLE_MOMS_HEELS] = true,
			[CollectibleType.COLLECTIBLE_MOMS_UNDERWEAR] = true,
			[CollectibleType.COLLECTIBLE_MONEY_EQUALS_POWER] = true,
			[CollectibleType.COLLECTIBLE_MY_REFLECTION] = true,
			[CollectibleType.COLLECTIBLE_PARASITE] = true,
			[CollectibleType.COLLECTIBLE_PHD] = true,
			[CollectibleType.COLLECTIBLE_SKATOLE] = true,
			[CollectibleType.COLLECTIBLE_SMALL_ROCK] = true,
			[CollectibleType.COLLECTIBLE_SPELUNKER_HAT] = true,
			[CollectibleType.COLLECTIBLE_SPIDER_BITE] = true,
			[CollectibleType.COLLECTIBLE_STEAM_SALE] = true,
			[CollectibleType.COLLECTIBLE_STEVEN] = true,
			[CollectibleType.COLLECTIBLE_SUPER_BANDAGE] = true,
			[CollectibleType.COLLECTIBLE_ROSARY] = true,
			[CollectibleType.COLLECTIBLE_WIRE_COAT_HANGER] = true,
			[CollectibleType.COLLECTIBLE_XRAY_VISION] = true,
			[CollectibleType.COLLECTIBLE_BLOODY_LUST] = true,
			[CollectibleType.COLLECTIBLE_DEAD_DOVE] = true,
			[CollectibleType.COLLECTIBLE_EPIC_FETUS] = true,
			[CollectibleType.COLLECTIBLE_MOMS_COIN_PURSE] = true,
			[CollectibleType.COLLECTIBLE_PAGEANT_BOY] = true,
			[CollectibleType.COLLECTIBLE_PEEPER] = true,
			[CollectibleType.COLLECTIBLE_SCOOPER] = true,
			[CollectibleType.COLLECTIBLE_PYRO] = true,
			[CollectibleType.COLLECTIBLE_SCAPULAR] = true,
			[CollectibleType.COLLECTIBLE_TECHNOLOGY] = true,
			[CollectibleType.COLLECTIBLE_TECH_X] = true,
			[CollectibleType.COLLECTIBLE_TECH_5] = true,
			[CollectibleType.COLLECTIBLE_HALO] = true,
			[CollectibleType.COLLECTIBLE_GUPPYS_TAIL] = true,
			[CollectibleType.COLLECTIBLE_MOMS_PURSE] = true,
			[CollectibleType.COLLECTIBLE_SPIRIT_OF_THE_NIGHT] = true,
			[CollectibleType.COLLECTIBLE_ANKH] = true,
			[CollectibleType.COLLECTIBLE_MITRE] = true,
			[CollectibleType.COLLECTIBLE_BOX] = true,
			[CollectibleType.COLLECTIBLE_MOMS_EYESHADOW] = true,
			[CollectibleType.COLLECTIBLE_IRON_BAR] = true,
			[CollectibleType.COLLECTIBLE_MIDAS_TOUCH] = true,
			[CollectibleType.COLLECTIBLE_FANNY_PACK] = true,
			[CollectibleType.COLLECTIBLE_SHARP_PLUG] = true,
			[CollectibleType.COLLECTIBLE_CHAMPION_BELT] = true,
			[CollectibleType.COLLECTIBLE_GNAWED_LEAF] = true,
			[CollectibleType.COLLECTIBLE_GUPPYS_COLLAR] = true,
			[CollectibleType.COLLECTIBLE_CEREMONIAL_ROBES] = true,
			[CollectibleType.COLLECTIBLE_OLD_BANDAGE] = true,
			[CollectibleType.COLLECTIBLE_BLACK_LOTUS] = true,
			[CollectibleType.COLLECTIBLE_TINY_PLANET] = true,
			[CollectibleType.COLLECTIBLE_CONTRACT_FROM_BELOW] = true,
			[CollectibleType.COLLECTIBLE_INFAMY] = true,
			[CollectibleType.COLLECTIBLE_20_20] = true,
			[CollectibleType.COLLECTIBLE_HIVE_MIND] = true,
			[CollectibleType.COLLECTIBLE_LITTLE_BAGGY] = true,
			[CollectibleType.COLLECTIBLE_BLOOD_CLOT] = true,
			[CollectibleType.COLLECTIBLE_SCREW] = true,
			[CollectibleType.COLLECTIBLE_HOT_BOMBS] = true,
			[CollectibleType.COLLECTIBLE_FIRE_MIND] = true,
			[CollectibleType.COLLECTIBLE_MISSING_PAGE_2] = true,
			[CollectibleType.COLLECTIBLE_ROBO_BABY_2] = true,
			[CollectibleType.COLLECTIBLE_VIRGO] = true,
			[CollectibleType.COLLECTIBLE_AQUARIUS] = true,
			[CollectibleType.COLLECTIBLE_MAGGYS_BOW] = true,
			[CollectibleType.COLLECTIBLE_STRANGE_ATTRACTOR] = true,
			[CollectibleType.COLLECTIBLE_CURSED_EYE] = true,
			[CollectibleType.COLLECTIBLE_MYSTERIOUS_LIQUID] = true,
			[CollectibleType.COLLECTIBLE_POLAROID] = true,
			[CollectibleType.COLLECTIBLE_NEGATIVE] = true,
			[CollectibleType.COLLECTIBLE_SAFETY_PIN] = true,
			[CollectibleType.COLLECTIBLE_LATCH_KEY] = true,
			[CollectibleType.COLLECTIBLE_MATCH_BOOK] = true,
			[CollectibleType.COLLECTIBLE_TOXIC_SHOCK] = true,
			[CollectibleType.COLLECTIBLE_BOMBER_BOY] = true,
			[CollectibleType.COLLECTIBLE_CRACK_JACKS] = true,
			[CollectibleType.COLLECTIBLE_MOMS_PEARLS] = true,
			[CollectibleType.COLLECTIBLE_MR_DOLLY] = true,
			[CollectibleType.COLLECTIBLE_CURSE_OF_THE_TOWER] = true,
			[CollectibleType.COLLECTIBLE_DEAD_EYE] = true,
			[CollectibleType.COLLECTIBLE_HOLY_LIGHT] = true,
			[CollectibleType.COLLECTIBLE_HOST_HAT] = true,
			[CollectibleType.COLLECTIBLE_PAY_TO_PLAY] = true,
			[CollectibleType.COLLECTIBLE_EDENS_BLESSING] = true,
			[CollectibleType.COLLECTIBLE_TRACTOR_BEAM] = true,
			[CollectibleType.COLLECTIBLE_PURITY] = true,
			[CollectibleType.COLLECTIBLE_ATHAME] = true,
			[CollectibleType.COLLECTIBLE_EMPTY_VESSEL] = true,
			[CollectibleType.COLLECTIBLE_BLACK_POWDER] = true,
			[CollectibleType.COLLECTIBLE_NIGHT_LIGHT] = true,
			[CollectibleType.COLLECTIBLE_PJS] = true,
			[CollectibleType.COLLECTIBLE_HEAD_OF_THE_KEEPER] = true,
			[CollectibleType.COLLECTIBLE_GLITTER_BOMBS] = true,
			[CollectibleType.COLLECTIBLE_MY_SHADOW] = true,
			[CollectibleType.COLLECTIBLE_LEAD_PENCIL] = true,
			[CollectibleType.COLLECTIBLE_LINGER_BEAN] = true,
			[CollectibleType.COLLECTIBLE_EYE_OF_GREED] = true,
			[CollectibleType.COLLECTIBLE_TAROT_CLOTH] = true,
			[CollectibleType.COLLECTIBLE_EYE_OF_BELIAL] = true,
			[CollectibleType.COLLECTIBLE_GLYPH_OF_BALANCE] = true,
			[CollectibleType.COLLECTIBLE_JACOBS_LADDER] = true,
			[CollectibleType.COLLECTIBLE_CAMO_UNDIES] = true,
			[CollectibleType.COLLECTIBLE_DUALITY] = true,
			[CollectibleType.COLLECTIBLE_EUCHARIST] = true,
			[CollectibleType.COLLECTIBLE_GREEDS_GULLET] = true,
			[CollectibleType.COLLECTIBLE_LITTLE_HORN] = true,
			[CollectibleType.COLLECTIBLE_SHARP_STRAW] = true,
			[CollectibleType.COLLECTIBLE_BOZO] = true,
			[CollectibleType.COLLECTIBLE_FAST_BOMBS] = true,
			[CollectibleType.COLLECTIBLE_DEATHS_LIST] = true,
			[CollectibleType.COLLECTIBLE_BLANKET] = true,
			[CollectibleType.COLLECTIBLE_MARROW] = true,
			[CollectibleType.COLLECTIBLE_DADS_RING] = true,
			[CollectibleType.COLLECTIBLE_BATTERY] = true,
			[CollectibleType.COLLECTIBLE_STOP_WATCH] = true,
			[CollectibleType.COLLECTIBLE_BROKEN_WATCH] = true,
			[CollectibleType.COLLECTIBLE_LAZARUS_RAGS] = true,
			[CollectibleType.COLLECTIBLE_MOMS_KEY] = true,
			[CollectibleType.COLLECTIBLE_MONSTROS_TOOTH] = true,
			[CollectibleType.COLLECTIBLE_SOUL] = true,
			[CollectibleType.COLLECTIBLE_120_VOLT] = true,
			[CollectibleType.COLLECTIBLE_BLOOD_OATH] = true,
			[CollectibleType.COLLECTIBLE_SOCKS] = true,
			[CollectibleType.COLLECTIBLE_MONSTRANCE] = true,
			[CollectibleType.COLLECTIBLE_SOL] = true,
			[CollectibleType.COLLECTIBLE_MERCURIUS] = true,
			[CollectibleType.COLLECTIBLE_ACT_OF_CONTRITION] = true,
			[CollectibleType.COLLECTIBLE_MEMBER_CARD] = true,
			[CollectibleType.COLLECTIBLE_BATTERY_PACK] = true,
			[CollectibleType.COLLECTIBLE_BIRD_CAGE] = true,
			[CollectibleType.COLLECTIBLE_BLOOD_BOMBS] = true,
			[CollectibleType.COLLECTIBLE_BIRDS_EYE] = true,
			[CollectibleType.COLLECTIBLE_EVIL_CHARM] = true,
			[CollectibleType.COLLECTIBLE_CONSOLATION_PRIZE] = true,
			[CollectibleType.COLLECTIBLE_LARYNX] = true,
			[CollectibleType.COLLECTIBLE_GUPPYS_EYE] = true,
			[CollectibleType.COLLECTIBLE_CRACKED_ORB] = true,
			[CollectibleType.COLLECTIBLE_C_SECTION] = true,
			[CollectibleType.COLLECTIBLE_SOUL_LOCKET] = true,
			[CollectibleType.COLLECTIBLE_BERSERK] = true,
			[CollectibleType.COLLECTIBLE_GLASS_EYE] = true,
		}
	)
	ccp:NullItemIDWhitelist(
		g.PLAYER_SPIRIT,
		{
			[NullItemID.ID_PUBERTY] = true,
			[NullItemID.ID_EMPTY_VESSEL] = true,
			[NullItemID.ID_BOOKWORM] = true,
			[NullItemID.ID_MOM] = true,
			[NullItemID.ID_DOUBLE_GUPPYS_EYE] = true,
			[NullItemID.ID_DOUBLE_GLASS_EYE] = true,
			[NullItemID.ID_CHRISTMAS] = true,
			[NullItemID.ID_BLINDFOLD] = true,
			[NullItemID.ID_BATWING_WINGS] = true
		}
	)
end

function modSupport:AddCoopGhostCompatibility()
	if CustomCoopGhost then
		CustomCoopGhost.ChangeSkin(g.PLAYER_DORKY, "dorky")
		CustomCoopGhost.AddCostume(g.PLAYER_DORKY, "dorky")
		CustomCoopGhost.ChangeSkin(g.PLAYER_SPIRIT, "spirit")
		CustomCoopGhost.AddCostume(g.PLAYER_SPIRIT, "spirit")
	end
end

function modSupport:AddPogCompatibility()
	if Poglite then
		local pogCostume = Isaac.GetCostumeIdByPath("gfx/characters/costume_dorky_pog.anm2")
		Poglite:AddPogCostume("DorkyPog", g.PLAYER_DORKY, pogCostume)
	end
end

function modSupport:AddNoCostumesCompatibility()
	if NoCostumes then
		addCostumeToIgnoreList("gfx/characters/costume_dorky.anm2")
		addCostumeToIgnoreList("gfx/characters/costume_dorky_tongueout.anm2")
		addCostumeToIgnoreList("gfx/characters/costume_dorky_flight.anm2")
		addCostumeToIgnoreList("gfx/characters/costume_dorky_pog.anm2")
		addCostumeToIgnoreList("gfx/characters/costume_spirit.anm2")
	end
end

---@param player EntityPlayer
function modSupport:OnPlayerInit(player, ccp)
	modSupport:AddCCPSupport(player, ccp)
	modSupport:AddCoopGhostCompatibility()
	modSupport:AddNoCostumesCompatibility()
	if player:GetPlayerType() == g.PLAYER_DORKY then
		modSupport:AddPogCompatibility()
	end
end

return modSupport
